grocery_item = "Grilled Chicken Salad"
print(grocery_item[0])
print(grocery_item[8])
print(grocery_item[16])
length_of_item = len(grocery_item)
print(grocery_item[-1])
print(grocery_item[-7])
print(grocery_item[-15])
first_char = (grocery_item [0])
second_char = (grocery_item [8])
third_char = (grocery_item [16])
last_char1 = (grocery_item [-1])
last_char2 = (grocery_item [-7])
last_char3 = (grocery_item [-15])
# Testing
print("First character of each word:", first_char, second_char, third_char)
print("Last character of each word:", last_char1, last_char2, last_char3)